
     
export const PERCENTAGE_CHART_DATASET: any[] = [
    {
       
        label: 'Supera',
        fill: false,
        backgroundColor: 'rgba(0, 255, 74, .5)',
        borderColor: 'rgba(0, 255, 74, .5)',
        borderCapStyle: 'butt',
        borderDash: [],
        borderDashOffset: 0.0,
        borderJoinStyle: 'miter',
        pointBorderColor: 'rgba(0, 0, 0, .5)',
        pointBackgroundColor: 'rgba(0, 255, 74, .5)',
        pointBorderWidth: 1,
        pointHoverRadius: 5,
        pointHoverBackgroundColor: 'rgba(0, 255, 74, .5)',
        pointHoverBorderColor: 'rgba(0, 0, 0, .5)',
        pointHoverBorderWidth: 2,
        pointStyle: 'rectRot',
        pointRadius: 1,
        pointHitRadius: 10,
        data: [],
        spanGaps: false,
        
    },
    {
        label: 'Logra',
        
        fill: false,
        backgroundColor: 'rgba(0, 0, 255, 1)',
        borderColor: 'rgba(0, 0, 255, 1)',
        borderCapStyle: 'butt',
        borderDash: [],
        borderDashOffset: 0.0,
        borderJoinStyle: 'miter',
        pointBorderColor: 'rgba(0, 0, 0, .5)',
        pointBackgroundColor: 'rgba(0, 0, 255, 1)',
        pointBorderWidth: 1,
        pointHoverRadius: 5,
        pointHoverBackgroundColor: 'rgba(0, 0, 255, 1)',
        pointHoverBorderColor: 'rgba(0, 0, 0, .5)',
        pointHoverBorderWidth: 2,
        pointRadius: 1,
        pointHitRadius: 10,
        data: [],
        spanGaps: false,
      
    },
    {
        label: 'Parcial',
        fill: false,
        backgroundColor: 'rgb(255, 191, 0)',
        borderColor: 'rgb(255, 191, 0)',
        borderCapStyle: 'butt',
        borderDash: [],
        borderDashOffset: 0.0,
        borderJoinStyle: 'miter',
        pointBorderColor: 'rgba(0, 0, 0, .5)',
        pointBackgroundColor: 'rgb(255, 191, 0)',
        pointBorderWidth: 1,
        pointHoverRadius: 5,
        pointHoverBackgroundColor: 'rgb(255, 191, 0)',
        pointHoverBorderColor: 'rgba(0, 0, 0, .5)',
        pointHoverBorderWidth: 2,
        pointRadius: 1,
        pointHitRadius: 10,
        data: [],
        spanGaps: false,
    },
    {
        label: 'No',
        fill: false,
        backgroundColor: 'rgba(255, 0, 0, 0.8)',
        borderColor: 'rgba(255, 0, 0, 0.8)',
        borderCapStyle: 'butt',
        borderDash: [],
        borderDashOffset: 0.0,
        borderJoinStyle: 'miter',
        pointBorderColor: 'rgba(0, 0, 0, .5)',
        pointBackgroundColor: 'rgba(255, 0, 0, 0.8)',
        pointBorderWidth: 1,
        pointHoverRadius: 5,
        pointHoverBackgroundColor: 'rgba(255, 0, 0, 0.8)',
        pointHoverBorderColor: 'rgba(0, 0, 0, .5)',
        pointHoverBorderWidth: 2,
        pointRadius: 1,
        pointHitRadius: 10,
        data: [],
        spanGaps: false,
    }
];


export const PERFORMANCE_CHART_DATASET: any[] = [
     
    {
        label: 'Buen resultado',
        fill: false,
        backgroundColor: 'rgba(0, 255, 74, .5)',
        borderColor: 'rgba(0, 255, 74, .5)',
        borderCapStyle: 'butt',
        borderDash: [],
        borderDashOffset: 0.0,
        borderJoinStyle: 'miter',
        pointBorderColor: 'rgba(0, 255, 74, .5)',
        pointBackgroundColor: '#fff',
        pointBorderWidth: 1,
        pointHoverRadius: 5,
        pointHoverBackgroundColor: 'rgba(0, 255, 74, 1)',
        pointHoverBorderColor: 'rgba(220,220,220,1)',
        pointHoverBorderWidth: 2,
        
        pointRadius: 1,
        pointHitRadius: 10,
        data: [],
        spanGaps: false,
        
    },
    {
        label: 'Mal resultado',
        fill: false,
        backgroundColor: 'rgba(255, 0, 0, 0.8)',
        borderColor: 'rgba(255, 0, 0, 0.8)',
        borderCapStyle: 'butt',
        borderDash: [],
        borderDashOffset: 0.0,
        borderJoinStyle: 'miter',
        pointBorderColor: 'rgba(255, 0, 0, 0.8)',
        pointBackgroundColor: '#fff',
        pointBorderWidth: 1,
        pointHoverRadius: 5,
        pointHoverBackgroundColor: 'rgba(75,192,192,1)',
        pointHoverBorderColor: 'rgba(220,220,220,1)',
        pointHoverBorderWidth: 2,
       
        pointRadius: 1,
        pointHitRadius: 10,
        data: [],
        spanGaps: false,
    }
  
];
